# Site
title:              Anders Ellern Bilgrau
bio:                'Hjemmesiden for mit lille statistiske konsulent biks'
description:        "Dette er hjemmesiden for min lille statistiske konsulent enkelmandsvirksomhed, der er dedikeret til at give en 'no bullshit' tilgang til dine statistiske problemer."
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   default

# Social
analytics-id:       "default"
twitter:            default
facebook:           default
instagram:          default
github:             AEBilgrau
stackoverflow:      1568306
linkedin:           aebilgrau

# personal
location:           Skovbrynet 13, 9530 Støvring, Danmark
phone:              +45 25 33 72 53
email:              anders.ellern.bilgrau@gmail.com

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [elements.html, mysite.Rproj, README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
