baseURL = "https://bilgrau.com"
languageCode = "da-dk"
defaultContentLanguage = "dk"
theme = "hermit"
enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true
rssLimit = 10  # Maximum number of items in the RSS feed.
#copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
# googleAnalytics = "UA-123-45"
# disqusShortname = "yourdiscussshortname"

title = "Anders Ellern Bilgrau"

[author]
  name = "Anders Ellern Bilgrau"
  
[languages.dk]
  weight = 0
  homeSubtitle = 'Statistiker, programmør, "data scientist"...'
  languageName = "Dansk"

[[languages.dk.menu.main]]
  name = "Om mig"
  url = "about/"
  weight = 10

[[languages.dk.menu.main]]
  name = "Blog"
  url = "posts/"
  weight = 20

[languages.en]
  weight = 1
  homeSubtitle = 'Statistician, programmer, "data scientist"...'
  languageName = "English"

[[languages.en.menu.main]]
  name = "About me"
  url = "en/about/"
  weight = 10

[[languages.en.menu.main]]
  name = "Posts"
  url = "en/posts/"
  weight = 20


[blackfriday]
  # hrefTargetBlank = true
  # noreferrerLinks = true
  # nofollowLinks = true

[taxonomies]
  tag = "tags"
  # Categories are disabled by default.

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 UTC"

  # Metadata mostly used in document's head
  # description = ""
  # images = [""]
  themeColor = "#495f5c"

  homeSubtitle = '"Data scientist" (statistician, programmer)'
  footerCopyright = ' · <a href="/">dansk</a> · <a href="/en/">english</a>'
  # bgImg = ""  # Homepage background-image URL

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  gitUrl = "https://github.com/AEBilgrau/AEBilgrau.github.io/commit/"

  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = false  # Set "text-align: justify" to `.content`.

  relatedPosts = false  # Add a related content section to all single posts page

  code_copy_button = true # Turn on/off the code-copy-button for code-fields
  
  # Add custom css
  # customCSS = ["css/foo.css", "css/bar.css"]

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.
  [[params.social]]
    name = "email"
    url = "mailto:anders.ellern.bilgrau@gmail.com"
  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/aebilgrau"
  [[params.social]]
    name = "github"
    url = "https://github.com/AEBilgrau"
  [[params.social]] 
    name = "stackoverflow"
    url = "https://stackoverflow.com/u/1568306"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/aebilgrau"
  [[params.social]]
    name = "google-scholar"
    url = "https://scholar.google.dk/citations?user=zQNl61YAAAAJ"
